server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yoonsla/spring-cloud
          search-paths: config/config-file/**
          default-label: main
          basedir: ./repo